package Janela_cadastro;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ead
 */
import java.awt.TextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.System.Logger;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    
    public Janela() {
        initComponents();
    }

    private int idAtual = -1; // id do registro atualmente selecionado para alterar ou deletar
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        SaveButton = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        CadastradosButton = new javax.swing.JToggleButton();
        BuscarButton = new javax.swing.JToggleButton();
        Alterar_DeletarButton = new javax.swing.JToggleButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro");

        jLabel2.setText("Nome :");

        jLabel3.setText("Email :");

        jLabel4.setText("Telefone :");

        jLabel5.setText("Tipo :");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Telefone", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tabela);

        CadastradosButton.setText("Cadastrados");
        CadastradosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastradosButtonActionPerformed(evt);
            }
        });

        BuscarButton.setText("Buscar ID");
        BuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });

        Alterar_DeletarButton.setText("Altera/Deletar");
        Alterar_DeletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alterar_DeletarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTipo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTele))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEmail))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(CadastradosButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BuscarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Alterar_DeletarButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(SaveButton)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CadastradosButton)
                            .addComponent(BuscarButton)
                            .addComponent(Alterar_DeletarButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastradosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastradosButtonActionPerformed

//        CadastroDAO cadastroDao = new CadastroDAO();
//        
//        try {
//            DefaultTableModel model = (DefaultTableModel) tabelMostrar.getModel();
//            model.setRowCount(0);
//            
//            List<Cadastro> usuarios = cadastroDao.listarPessoa();
//            
//            for (Cadastro u : usuarios){
//                model.addRow(new Object[]{
//                    u.getNome(),
//                    u.getEmail(),
//                    u.getTelefone(),
//                    u.getTipo()
//                });
//                
//            }
//            
//            
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(this,"Erro ao buscar dados: "+e.getMessage()
//                    , "Erro", JOptionPane.ERROR_MESSAGE);
//        }     

      CadastroDAO cadastroDao = new CadastroDAO();
    
    try {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setRowCount(0);  // limpa linhas existentes
        
        List<Cadastro> usuarios = cadastroDao.listarPessoa();
        
        for (Cadastro u : usuarios){
            model.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getEmail(),
                u.getTelefone(),
                u.getTipo()
            });
        }
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,"Erro ao buscar dados: "+e.getMessage()
                , "Erro", JOptionPane.ERROR_MESSAGE);
    } 
        
    }//GEN-LAST:event_CadastradosButtonActionPerformed

    
    
    
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
     
        CadastroDAO cadastroDao = new CadastroDAO();
        
        
        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String telefone = txtTele.getText().trim();
        String tipoUsuario = txtTipo.getText().trim();
        
        if(nome.isEmpty() || email.isEmpty() || telefone.isEmpty() || 
                tipoUsuario.isEmpty()){
            
            JOptionPane.showMessageDialog(this, 
                    "Preencha todos os campos antes de salvar",
                    "Campos obrigatórios",JOptionPane.WARNING_MESSAGE);
            
            return;
        }
        
        Cadastro pessoa = new Cadastro(0, nome, email, telefone, tipoUsuario);
        
        try {
            cadastroDao.criaPessoa(pessoa);
            JOptionPane.showMessageDialog(this, "Usuário salvo com sucesso!"
                    ,"Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            
//            Logger.getLogger(getClass().getName()).log(Level.SEVERE, 
//                    "Erro ao salvar usúario",ex);
            
            JOptionPane.showMessageDialog(this, 
                    "Não fois possível salvar o usúario.","Detalhes: "
                            +ex.getMessage(),JOptionPane.INFORMATION_MESSAGE);
            
        
            
        }     
            
        

    }//GEN-LAST:event_SaveButtonActionPerformed

    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed

//            CadastroDAO cadastroDao = new CadastroDAO();
//            tabelMostrar = new javax.swing.JTable();
//
//            DefaultTableModel model = (DefaultTableModel) tabelMostrar.getModel();
//                model.setRowCount(0);
//
//            String valor =  JOptionPane.showInputDialog("insira um valor");
//
//            int idBuscador = Integer.parseInt(valor);
//
//            try{
//
//               Cadastro u = cadastroDao.buscarPessoaPorId(idBuscador);
//
//                if (u != null) {
//                    model.addRow(new Object[]{
//                        u.getNome(),
//                        u.getEmail(),
//                        u.getTelefone(),
//                        u.getTipo()
//                    });
//                } else {
//                    JOptionPane.showMessageDialog(this,"Erro ao buscar dados! "
//                        , "Erro", JOptionPane.ERROR_MESSAGE);
//                }
//
//            }catch(SQLException e){
//                JOptionPane.showMessageDialog(this,"Erro ao buscar dados: "+e.getMessage()
//                        , "Erro", JOptionPane.ERROR_MESSAGE);
//            }
//
//        }//GEN-LAST:;;
//

    CadastroDAO cadastroDao = new CadastroDAO();
    DefaultTableModel model = (DefaultTableModel) tabela.getModel();
    model.setRowCount(0);  // limpa tabela antes
    
    try {
        String valor = JOptionPane.showInputDialog(this, "Informe o ID para busca:");
        if (valor == null || valor.trim().isEmpty()) {
            return; // cancelou ou vazio
        }
        
        int idBuscado = Integer.parseInt(valor.trim());
        
        Cadastro resultado = cadastroDao.buscarPessoaPorId(idBuscado);
        
        if (resultado != null) {
            // Atualiza tabela com o resultado
            model.addRow(new Object[]{
                resultado.getId(),
                resultado.getNome(),
                resultado.getEmail(),
                resultado.getTelefone(),
                resultado.getTipo()
            });
            
            // Preenche campos de texto para edição
            txtNome.setText(resultado.getNome());
            txtEmail.setText(resultado.getEmail());
            txtTele.setText(resultado.getTelefone());
            txtTipo.setText(resultado.getTipo());
            
            idAtual = resultado.getId(); // salva o ID atual para alterar ou deletar
            
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum registro encontrado para o ID: " + idBuscado);
            idAtual = -1;
            txtNome.setText("");
            txtEmail.setText("");
            txtTele.setText("");
            txtTipo.setText("");
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido! Insira um número inteiro.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar no banco: " + e.getMessage());
    }
    
    }//GEN-LAST:event_BuscarButtonActionPerformed

    private void Alterar_DeletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alterar_DeletarButtonActionPerformed
       
        
        
        
        
    }//GEN-LAST:event_Alterar_DeletarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Alterar_DeletarButton;
    private javax.swing.JToggleButton BuscarButton;
    private javax.swing.JToggleButton CadastradosButton;
    private javax.swing.JToggleButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTele;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
